os: osx
language: swift
osx_image: xcode12.2
# branch safelist
branches:
  only:
    - master
    - /^release\/.*$/
# install dependencies
install:
  - bundle install
# jobs and stages to run
jobs:
  include:
    - stage: Deploy
      name: Deploy to App Store
      script:
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane deploy_to_app_store
      if: branch =~ /^release\/.*$/
