default_platform(:ios)
before_all do
  xcversion(version: "11.1")
end
setup_travis
def version_number
  if ENV["TRAVIS_BRANCH"].match?(/^release\/.*$/)
    return ENV["TRAVIS_BRANCH"].split("/").last
  else
    return get_version_number
  end
end
platform :ios do
  desc "Installs the certificates locally"
  private_lane :install_certificates do
    tmp_keychain = "temporary_keychain"
    create_keychain(
      name: tmp_keychain,
      password: tmp_keychain,
      default_keychain: true,
      timeout: 3600,
      unlock: true,
    )
    match(
      type: "appstore",
      keychain_name: tmp_keychain,
      keychain_password: tmp_keychain,
      readonly: true
    )
  end
  desc 'Deploys KELO to App Store'
  lane :deploy_to_app_store do
    install_certificates
    increment_version_number(version_number: version_number)
    increment_build_number(build_number: latest_testflight_build_number + 1)
    gym(
      scheme: "KELO",
      clean: true
    )
    deliver(
      submit_for_review: true,
      reject_if_possible: true,
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )
  end
end
